# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  pathtoproj: variable1

stages:
- stage: stage1_build
  jobs:
  - job: build_job1
    steps:
    - bash: echo this is how we use a variable => $(pathtoproj)
      displayName: 'Run a one-line script'
      
    # - task: DotNetCoreCLI@2
    #   inputs:
    #     command: 'build'
    #     projects: '$(pathtoproj)'
    #     arguments: 'arghere'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

  - job: build_job2
    displayName: job2
    steps:
    # - script: echo this is script.job2
    #   displayName: 'Run a one-line script'

    - script: |
        echo this is script.job2.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: stage2_test
  jobs:
  - job: test_job1
    steps:
      - bash: echo stage2.step1 is how we use a variable => $(pathtoproj)
        displayName: 'Run a one-line script'
      - script: 
          echo this is script2.job2
        displayName: 'ran the stage2.script2'
    
- stage: stage3_deploy
  jobs:
  - job: deploy_job1
    steps:
      - bash: echo stage2.step1 is how we use a variable => $(pathtoproj)
        displayName: 'Run a one-line script'
      - script: 
          echo this is script2.stagedeploy.job1
        displayName: 'ran the stage3.script2'
  dependsOn: []
    